[python-zope-exceptions]
source = "git"
git = "https://github.com/zopefoundation/zope.exceptions.git"
